# Generated by Django 4.1.3 on 2022-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairmen',
            name='pic',
            field=models.FileField(default='set.png', upload_to='media/images/'),
        ),
    ]
