# Generated by Django 4.1.3 on 2022-12-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_chairmen_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairmen',
            name='pic',
            field=models.FileField(default='media/set.png', upload_to='media/images/'),
        ),
    ]
