# Generated by Django 4.1.3 on 2022-12-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_chairmen_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chairmen',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
