# Generated by Django 4.1.3 on 2023-01-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_event_alter_notice_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
