# Generated by Django 4.1.3 on 2023-01-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('pic', models.FileField(blank=True, default='media/set.png', null=True, upload_to='media/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
