# Generated by Django 4.1.3 on 2022-12-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chairmen_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairmen',
            name='pic',
            field=models.FileField(default='images/set.jpg', upload_to='media/images/'),
        ),
    ]
