# Generated by Django 4.1.3 on 2022-12-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_chairmen_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chairmen',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
