# Generated by Django 4.1.3 on 2022-12-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chairmen_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('family_member', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('block_no', models.CharField(max_length=30)),
                ('house_no', models.CharField(max_length=30)),
                ('pic', models.FileField(default='media/images/set.jpg', upload_to='media/images/')),
                ('urser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
