# Generated by Django 4.1.3 on 2023-01-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
