# Generated by Django 4.1.3 on 2023-01-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_member_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(default='media/images/set.jpg', upload_to='media/images/'),
        ),
    ]
