# Generated by Django 4.1.3 on 2023-01-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_member_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='pic',
        ),
    ]
